# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cucumber-rails/all/cucumber-rails.rbi
#
# cucumber-rails-1.7.0
class Rails::Application < Rails::Engine
  def __cucumber_orig_initialize__(group = nil); end
end
class ActionController::Base < ActionController::Metal
  def allow_rescue; end
  def allow_rescue=(obj); end
  def self.allow_rescue; end
  def self.allow_rescue=(obj); end
end
class ActionDispatch::ShowExceptions
  def __cucumber_orig_call__(env); end
end
