# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk-content-schema-test-helpers/all/govuk-content-schema-test-helpers.rbi
#
# govuk-content-schema-test-helpers-1.6.1
module GovukContentSchemaTestHelpers
  def self.configuration; end
  def self.configuration=(config); end
  def self.configure; end
end
class GovukContentSchemaTestHelpers::ConfigurationError < StandardError
end
class GovukContentSchemaTestHelpers::Configuration
  def project_root; end
  def project_root=(arg0); end
  def schema_type; end
  def schema_type=(arg0); end
end
class GovukContentSchemaTestHelpers::Examples
  def check_an_example_file_exists(path, legacy_path); end
  def example_path(format, example_name); end
  def get(format, example_name); end
  def get_all_for_format(schema_name); end
  def get_all_for_formats(schema_names); end
  def initialize; end
  def legacy_example_path(format, example_name); end
end
class GovukContentSchemaTestHelpers::ImproperlyConfiguredError < RuntimeError
end
module GovukContentSchemaTestHelpers::Util
  def self.check_govuk_content_schemas_path!; end
  def self.formats; end
  def self.govuk_content_schemas_path; end
end
class GovukContentSchemaTestHelpers::Validator
  def errors; end
  def initialize(schema_name, variant, document); end
  def schema_path; end
  def valid?; end
end
