# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk_publishing_components/all/govuk_publishing_components.rbi
#
# govuk_publishing_components-17.4.0
module GovukPublishingComponents
  def self.configure; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.render(component, options = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
module GovukPublishingComponents::Config
  def application_javascript; end
  def application_javascript=(obj); end
  def application_print_stylesheet; end
  def application_print_stylesheet=(obj); end
  def application_stylesheet; end
  def application_stylesheet=(obj); end
  def component_guide_title; end
  def component_guide_title=(obj); end
  def self.application_javascript; end
  def self.application_javascript=(obj); end
  def self.application_print_stylesheet; end
  def self.application_print_stylesheet=(obj); end
  def self.application_stylesheet; end
  def self.application_stylesheet=(obj); end
  def self.component_directory_name; end
  def self.component_guide_title; end
  def self.component_guide_title=(obj); end
  def self.gem_directory; end
end
class GovukPublishingComponents::Engine < Rails::Engine
end
module GovukPublishingComponents::Presenters
end
class GovukPublishingComponents::Presenters::SharedHelper
  def get_heading_level; end
  def get_margin_bottom; end
  def heading_level; end
  def initialize(local_assigns); end
  def margin_bottom; end
  def options; end
end
class GovukPublishingComponents::Presenters::Attachment
  def alternative_format_contact_email; end
  def attachment_data; end
  def content_type; end
  def content_type_abbr; end
  def content_type_name; end
  def document?(*args, &block); end
  def file_size; end
  def initialize(attachment_data); end
  def number_of_pages; end
  def opendocument?(*args, &block); end
  def spreadsheet?(*args, &block); end
  def title; end
  def url; end
end
class GovukPublishingComponents::Presenters::Attachment::SupportedContentType
  def abbr; end
  def content_type; end
  def content_type_data; end
  def document?; end
  def initialize(content_type_data); end
  def name; end
  def opendocument?; end
  def self.find(content_type, extension = nil); end
  def spreadsheet?; end
end
class GovukPublishingComponents::Presenters::Attachment::UnsupportedContentType
  def abbr; end
  def content_type; end
  def document?; end
  def initialize(content_type:); end
  def name; end
  def opendocument?; end
  def spreadsheet?; end
end
class GovukPublishingComponents::Presenters::Breadcrumbs
  def breadcrumbs; end
  def initialize(breadcrumbs, request_path); end
  def item_list_element; end
  def request_path; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::Breadcrumb
  def [](*args, &block); end
  def aria_current; end
  def crumb; end
  def index; end
  def initialize(crumb, index); end
  def is_link?; end
  def item_list_element(request_path); end
  def list_item_item(request_path); end
  def path; end
  def tracking_data(breadcrumbs_length); end
  extend Forwardable
end
class GovukPublishingComponents::Presenters::ButtonHelper
  def button_type; end
  def css_classes; end
  def data_attributes; end
  def destructive; end
  def href; end
  def html_options; end
  def info_text; end
  def initialize(local_assigns); end
  def inline_layout; end
  def link?; end
  def margin_bottom; end
  def rel; end
  def secondary; end
  def secondary_quiet; end
  def start; end
  def target; end
  def text; end
  def title; end
  def type; end
end
class GovukPublishingComponents::Presenters::ContextualNavigation
  def breadcrumbs; end
  def content_has_curated_related_items?; end
  def content_is_a_specialist_document?; end
  def content_is_tagged_to_a_live_taxon?; end
  def content_item; end
  def content_tagged_to_a_finder?; end
  def content_tagged_to_a_reasonable_number_of_step_by_steps?; end
  def content_tagged_to_current_step_by_step?; end
  def content_tagged_to_mainstream_browse_pages?; end
  def content_tagged_to_other_step_by_steps?; end
  def initialize(content_item, request); end
  def query_parameters; end
  def request_path; end
  def simple_smart_answer?; end
  def step_nav_helper; end
  def taxon_breadcrumbs; end
end
class GovukPublishingComponents::Presenters::RelatedNavigationHelper
  def calculate_section_link_limit(links); end
  def construct_section_heading(section_title); end
  def content_item_details_for(key); end
  def content_item_links_for(key, only: nil); end
  def detailed_guide?; end
  def initialize(options = nil); end
  def related_contacts; end
  def related_document_collections; end
  def related_external_links; end
  def related_guides; end
  def related_items; end
  def related_legacy_topics; end
  def related_mainstream_content; end
  def related_navigation; end
  def related_navigation?; end
  def related_statistical_data_sets; end
  def related_taxons; end
  def related_topical_events; end
  def related_topics; end
  def related_world_locations; end
  def remaining_link_count(links); end
  def section_css_class(css_class, section_title, link = nil); end
  def section_data_track_count(section_title); end
  def section_heading_level; end
end
class GovukPublishingComponents::Presenters::StepByStepNavHelper
  def create_context(context); end
  def create_list_item_content(link); end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def external_url?(href); end
  def generate_step_nav_id(step_title); end
  def get_list_element(style); end
  def get_list_style(style); end
  def link_active(active); end
  def link_href(active, href); end
  def link_text(active, text); end
  def link_with_step_nav_query_parameter(href); end
  def list(element); end
  def paragraph(text); end
  def render_step_nav_element(element, options); end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::PageWithStepByStepNavigation
  def active_step_by_step; end
  def active_step_by_step?; end
  def active_step_nav_content_id; end
  def also_part_of_step_nav; end
  def configure_for_sidebar(step_nav_content); end
  def content_item; end
  def current_path; end
  def current_step_nav; end
  def format_related_links(step_by_step_navs); end
  def header; end
  def initialize(content_store_response, current_path, query_parameters = nil); end
  def parsed_related_to_step_navs; end
  def parsed_secondary_to_step_navs; end
  def parsed_step_navs; end
  def primary_step_by_steps?; end
  def related_links; end
  def related_to_step_navs; end
  def secondary_step_by_step; end
  def secondary_step_by_step?; end
  def secondary_step_by_steps; end
  def show_also_part_of_step_nav?; end
  def show_header?; end
  def show_related_links?; end
  def show_related_links_for_secondary_step_by_steps?; end
  def show_secondary_step_by_step?; end
  def show_sidebar?; end
  def sidebar; end
  def step_navs; end
  def step_navs_combined_list; end
  def steps; end
end
class GovukPublishingComponents::Presenters::StepByStepModel
  def base_path; end
  def content; end
  def content_id; end
  def content_item; end
  def initialize(content_item); end
  def steps; end
  def title; end
end
class GovukPublishingComponents::Presenters::ContentBreadcrumbsBasedOnParent
  def all_parents; end
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
end
class GovukPublishingComponents::Presenters::ContentBreadcrumbsBasedOnTaxons
  def all_parents; end
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
end
class GovukPublishingComponents::Presenters::CheckboxesHelper
  def checkbox_markup(checkbox, index); end
  def css_classes; end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def error; end
  def fieldset_describedby; end
  def has_conditional; end
  def has_nested; end
  def heading_markup; end
  def hint_text; end
  def id; end
  def initialize(options); end
  def items; end
  def list_classes; end
  def name; end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  def should_have_fieldset; end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::SelectHelper
  def data_tracking?; end
  def get_options; end
  def initialize(options); end
  def option_markup; end
  def options; end
  def options_data_attribute(attributes); end
  def selected_option; end
end
class GovukPublishingComponents::Presenters::MetaTags
  def add_core_tags(meta_tags); end
  def add_organisation_tags(meta_tags); end
  def add_political_tags(meta_tags); end
  def add_step_by_step_tags(meta_tags); end
  def add_taxonomy_tags(meta_tags); end
  def content_item; end
  def details; end
  def has_content_history?; end
  def initialize(content_item, local_assigns); end
  def links; end
  def local_assigns; end
  def meta_tags; end
  def root_taxon_slugs(content_item); end
  def should_strip_dates_pii?(content_item, local_assigns); end
  def should_strip_postcode_pii?(content_item, local_assigns); end
end
class GovukPublishingComponents::Presenters::ContentItem
  def ==(other); end
  def as_taxonomy_sidebar_link; end
  def base_path; end
  def content_id; end
  def content_store_response; end
  def curated_taxonomy_sidebar_links; end
  def description; end
  def eql?(other); end
  def external_links; end
  def filter_link_type(links, type); end
  def hash; end
  def initialize(content_store_response); end
  def mainstream_browse_pages; end
  def parent; end
  def parent_taxon; end
  def parent_taxons; end
  def phase_is_live?(taxon); end
  def quick_links; end
  def related_collections; end
  def related_links; end
  def related_ordered_items; end
  def related_organisations; end
  def related_other_contacts; end
  def related_statistical_data_sets; end
  def related_topical_events; end
  def related_topics; end
  def related_world_locations; end
  def related_worldwide_organisations; end
  def taxon_links; end
  def title; end
end
class GovukPublishingComponents::Presenters::TranslationNavHelper
  def has_translations?; end
  def initialize(local_assigns); end
  def margin_class; end
  def tracking_is_present?; end
  def translations; end
end
class GovukPublishingComponents::Presenters::SubscriptionLinksHelper
  def component_data_is_valid?; end
  def email_signup_link; end
  def email_signup_link_data_attributes; end
  def email_signup_link_text; end
  def feed_box_id; end
  def feed_link; end
  def feed_link_box_value; end
  def feed_link_data_attributes; end
  def feed_link_text; end
  def initialize(local_assigns); end
  def tracking_is_present?; end
end
class GovukPublishingComponents::Presenters::Page
  def base_path; end
  def body; end
  def canonical_url; end
  def content_item; end
  def description; end
  def document_type; end
  def has_image?; end
  def image_alt_text; end
  def image_placeholders; end
  def image_url; end
  def initialize(local_assigns); end
  def local_assigns; end
  def logo_url; end
  def schema; end
  def title; end
end
class GovukPublishingComponents::Presenters::ArticleSchema
  def body; end
  def initialize(page); end
  def page; end
  def search_action; end
  def search_description; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::CreativeWorkSchema
  def about; end
  def author_schema; end
  def collection_pages(linked_type); end
  def document_collections; end
  def fetch_collection_pages(linked_type); end
  def has_part; end
  def image_schema; end
  def initialize(page); end
  def is_part_of; end
  def linked_page(step_by_step); end
  def linked_taxons; end
  def live_taxons; end
  def page; end
  def presenter; end
  def publishing_organisation; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::HasPartSchema
  def has_part_url; end
  def initialize(has_part_url); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::IsPartOfSchema
  def initialize(is_part_of_url); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::NewsArticleSchema
  def initialize(page); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::OrganisationSchema
  def initialize(page); end
  def linked_org(url); end
  def members; end
  def minister_url(minister); end
  def ministers; end
  def ministers_with_grouped_roles; end
  def organisation_facet_params; end
  def page; end
  def parent_organisations; end
  def person_schema_for_minister(minister); end
  def related_organisations(link_type, schema_name); end
  def role_for_minister(minister); end
  def role_url(minister); end
  def search_action; end
  def search_description; end
  def slug; end
  def structured_data; end
  def sub_organisations; end
  def website_root; end
end
class GovukPublishingComponents::Presenters::PersonSchema
  def image_schema; end
  def initialize(page); end
  def page; end
  def presenter; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::PotentialSearchActionSchema
  def description; end
  def facet_params; end
  def initialize(facet_params, description); end
  def search_template; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::SearchResultsPageSchema
  def initialize(page); end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::SchemaOrg
  def initialize(page); end
  def page; end
  def structured_data; end
end
class GovukPublishingComponents::Presenters::HeadingHelper
  def classes; end
  def heading_tag; end
  def id; end
  def initialize(options); end
end
class GovukPublishingComponents::Presenters::ContentsListHelper
  def wrap_numbers_with_spans(content_item_link); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  include ActionView::Helpers::SanitizeHelper
end
class GovukPublishingComponents::Presenters::ImageCardHelper
  def context; end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def description; end
  def extra_links; end
  def extra_links_no_indent; end
  def heading_text; end
  def href; end
  def href_data_attributes; end
  def image; end
  def initialize(local_assigns); end
  def is_tracking?; end
  def large; end
  def metadata; end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::OrganisationLogoHelper
  def crest; end
  def debug_missing_translation; end
  def debug_missing_translation=(obj); end
  def image; end
  def initialize(local_assigns); end
  def logo_container_class; end
  def logo_content; end
  def logo_image_alt; end
  def logo_image_src; end
  def name; end
  def self.debug_missing_translation; end
  def self.debug_missing_translation=(obj); end
  def url; end
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::SanitizeHelper::ClassMethods
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Context
  include ActionView::Helpers
  include ActionView::Helpers::AssetTagHelper
  include ActionView::Helpers::FormHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::FormTagHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::TranslationHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::Presenters::HighlightBoxesHelper
  def data_tracking?; end
  def initialize(options); end
end
class GovukPublishingComponents::Presenters::TaxonomyListHelper
  def image_card_data; end
  def initialize(image_cards); end
end
class GovukPublishingComponents::Presenters::CookieBannerHelper
  def initialize(local_assigns); end
  def local_assigns; end
  def message; end
end
module GovukPublishingComponents::AppHelpers
end
class GovukPublishingComponents::AppHelpers::TaxonBreadcrumbs
  def all_parents; end
  def breadcrumbs; end
  def content_item; end
  def initialize(content_item); end
end
class GovukPublishingComponents::AppHelpers::TaxonBreadcrumbs::ContentItem
  def base_path; end
  def content_item; end
  def initialize(content_item); end
  def parent_taxon; end
  def phase_is_live?(taxon); end
  def title; end
end
class GovukPublishingComponents::AppHelpers::TableHelper
  def self.helper(context, caption = nil, opt = nil); end
end
class GovukPublishingComponents::AppHelpers::TableHelper::TableBuilder
  def body; end
  def cell(str, opt = nil); end
  def head; end
  def header(str, opt = nil); end
  def initialize(tag); end
  def row; end
  def tag; end
  extend ActionView::Helpers::UrlHelper::ClassMethods
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::UrlHelper
end
class GovukPublishingComponents::AppHelpers::BrandHelper
  def border_color_class; end
  def brand_class; end
  def color_class; end
  def initialize(brand); end
end
class GovukPublishingComponents::AppHelpers::Environment
  def self.current_acceptance_environment; end
end
