# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk_frontend_toolkit/all/govuk_frontend_toolkit.rbi
#
# govuk_frontend_toolkit-8.2.0
module GovUKFrontendToolkit
end
class GovUKFrontendToolkit::Engine < Rails::Engine
end
