# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk_test/all/govuk_test.rbi
#
# govuk_test-0.5.0
module GovukTest
  def self.configure(options = nil); end
end
