# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk_document_types/all/govuk_document_types.rbi
#
# govuk_document_types-0.9.1
module GovukDocumentTypes
  def self.subgroup_document_types(*subgroup_ids); end
  def self.supergroup_document_types(*supergroup_ids); end
  def self.supergroup_subgroups(*supergroup_ids); end
  def self.supergroups(ids:); end
  def self.supertypes(document_type:); end
end
class GovukDocumentTypes::TranslationsRailtie < Rails::Railtie
  def self.add(pattern); end
  def self.pattern_from(args); end
end
