# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk-lint/all/govuk-lint.rbi
#
# govuk-lint-3.11.2
module Govuk
end
module Govuk::Lint
end
