# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/govuk_schemas/all/govuk_schemas.rbi
#
# govuk_schemas-3.2.0
module GovukSchemas
end
class GovukSchemas::Schema
  def self.all(schema_type: nil); end
  def self.find(schema); end
  def self.location_for_schema_name(schema); end
  def self.random_schema(schema_type:); end
  def self.schema_names; end
end
module GovukSchemas::Utils
  def self.parameterize(string); end
  def self.stringify_keys(hash); end
end
module GovukSchemas::Random
  def self.anchor; end
  def self.base_path; end
  def self.bool; end
  def self.govuk_subdomain_url; end
  def self.random_identifier(separator:); end
  def self.string(minimum_chars = nil, maximum_chars = nil); end
  def self.string_for_regex(pattern); end
  def self.string_for_type(type); end
  def self.time; end
  def self.uri; end
end
class GovukSchemas::RandomItemGenerator
  def generate_random_array(props); end
  def generate_random_object(subschema); end
  def generate_random_string(props); end
  def generate_value(props); end
  def initialize(schema:); end
  def lookup_json_pointer(ref); end
  def payload; end
end
class GovukSchemas::RandomExample
  def error_message(item, errors, customised = nil); end
  def initialize(schema:); end
  def payload; end
  def self.for_schema(schema_key_value, &block); end
  def validation_errors_for(item); end
end
class GovukSchemas::DocumentTypes
  def self.valid_document_types; end
end
class GovukSchemas::Example
  def self.examples_path(schema_name); end
  def self.find(schema_name, example_name:); end
  def self.find_all(schema_name); end
end
class GovukSchemas::InvalidContentGenerated < Exception
end
