# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jasmine-core/all/jasmine-core.rbi
#
# jasmine-core-3.4.0
module Jasmine
end
module Jasmine::Core
  def self.boot_dir; end
  def self.boot_files; end
  def self.core_spec_files; end
  def self.css_files; end
  def self.html_spec_files; end
  def self.images_dir; end
  def self.js_files; end
  def self.node_boot_files; end
  def self.node_spec_files; end
  def self.path; end
  def self.spec_files(type); end
end
