# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jasmine-rails/all/jasmine-rails.rbi
#
# jasmine-rails-0.15.0
module JasmineRails
  def self.css_dir; end
  def self.css_files; end
  def self.each_dir(root, &block); end
  def self.each_spec_dir(&block); end
  def self.filter_files(root_dir, patterns); end
  def self.force_ssl; end
  def self.include_dir; end
  def self.initialize_jasmine_config_if_absent(path); end
  def self.jasmine_config; end
  def self.phantom_options; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.reload_jasmine_config; end
  def self.reporter_files(types_string); end
  def self.route_path; end
  def self.spec_dir; end
  def self.spec_files; end
  def self.src_dir; end
  def self.table_name_prefix; end
  def self.tmp_dir; end
  def self.use_phantom_gem?; end
  def self.use_relative_model_naming?; end
end
class JasmineRails::Engine < Rails::Engine
end
